FROM node:20-bookworm-slim

WORKDIR /app

COPY package.json package-lock.json ./
COPY server/package.json server/package.json
COPY shared/package.json shared/package.json
RUN npm ci

COPY . .

RUN npm run prisma:generate --workspace server && npm run build --workspace shared && npm run build --workspace server

ENV NODE_ENV=production

EXPOSE 4000

CMD ["npm", "run", "start", "--workspace", "server"]
