FROM node:20-alpine

WORKDIR /app
ENV NODE_ENV=production

COPY package.json package-lock.json ./
COPY server/package.json server/package.json
COPY shared/package.json shared/package.json
RUN npm install

COPY . .

RUN npm run prisma:generate --workspace server && npm run build --workspace shared && npm run build --workspace server

EXPOSE 4000

CMD ["npm", "run", "start", "--workspace", "server"]
